// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmtnnnigdziadnwdksie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdG5ubmlnZHppYWRud2Rrc2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODk2NzgsImV4cCI6MjA3MTM2NTY3OH0.DP1hl9xzUalkHiXwDU1CRV9EgpDdJPGJ3r5NMtEyCC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});